[package]
name = "pwa_temp"
version = "0.1.0"
edition = "2018"


[dependencies]
chrono = "0.4.19"
gloo = "0.3.0"
json = "0.12.4"
plotters = "0.3.1"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
web3 = "0.17.0"